AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'examples/*'
    - 'spec/**/*'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
